spring:
  application:
    name: gateway-service
  config:
    import:
      - nacos:gateway-service.yaml
      - nacos:routing-rules.yaml
      - nacos:redis.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.186:8848
      config:
        server-addr: 192.168.0.186:8848
        file-extension: yaml
        group: DEFAULT_GROUP
  logging:
    level:
      org.springframework.cloud.gateway: TRACE
      org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE